### ISSUE TITLE
Support empty key.id (empty string)

### ISSUE THREAD

**Issue by hueniverse** [mshick/catbox-multilevel#1]
Catbox is moving to allow empty string as a valid key. Need to make sure this supports it.

**Comment by mshick** [comment]
Sure thing. Thanks for the heads up.

**Comment by mshick** [comment]
I've added a passing test for `key.id` as an empty string. `catbox-memory` and `catbox-redis` each seem to still expect `key` to be an object, so I'm following that. Please let me know if I missed something there.
